### ISSUE TITLE
Test Cases don't seem to run

### ISSUE THREAD

**Issue by DakshChhokra** [exercism/javascript#692]
The test cases don't seem to run for the collatz-conjecture problem on the js track. The furthest I can get on the terminal after typing in npm test is here
` RUNS  ./collatz-conjecture.spec.js`

**Comment by tejasbubane** [comment]
Hi @DakshChhokra, I see the following after running `npm test`:

```
> exercism-javascript@0.0.0 test /Users/tejas.bubane/exercism_submissions/javascript/collatz-conjecture
> jest --no-cache ./*

 FAIL  ./collatz-conjecture.spec.js
  steps()
    ✕ zero steps for one (3ms)
    ○ skipped divide if even
    ○ skipped even and odd steps
    ○ skipped Large number of even and odd steps
    ○ skipped zero is an error
    ○ skipped negative value is an error

  ● steps() › zero steps for one

    Remove this statement and implement this function

      5 |
      6 | export const steps = () => {
    > 7 |   throw new Error("Remove this statement and implement this function");
        |         ^
      8 | };
      9 |

      at steps (collatz-conjecture.js:7:9)
      at Object.<anonymous> (collatz-conjecture.spec.js:5:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 5 skipped, 6 total
Snapshots:   0 total
Time:        1.757s
Ran all test suites matching /.\/README.md|.\/babel.config.js|.\/collatz-conjecture.js|.\/collatz-conjecture.spec.js|.\/node_modules|.\/package-lock.json|.\/package.json/i.
npm ERR! Test failed.  See above for more details.
```

All but the first test are skipped. You are supposed to unskip each test and try to make them pass.

If you still face issues, let me know which OS & node version you are using and what is the error that you see.

**Comment by tejasbubane** [comment]
@DakshChhokra Are you still facing the issue?

**Comment by tejasbubane** [comment]
Closing due to no reply.
